title: Kisakoodaus
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
